import { createElement } from 'lwc';
import MeetingDataTable from 'c/meetingDataTable';

describe('c-meeting-data-table', () => {
    afterEach(() => {

        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        
        const element = createElement('c-meeting-data-table', {
            is: MeetingDataTable
        });

                document.body.appendChild(element);

        
        expect(1).toBe(1);
    });
});
